apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: hfat
  name: hfat
spec:
  containers:
  - image: huggingface/autotrain-advanced
  #- image: nvidia/cuda:12.1.1-cudnn8-runtime-ubuntu22.04 
    name: hfat
    command: ["tail","-f","/dev/null"]
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  imagePullSecrets:
  - name: dockerpullsec
  nodeSelector:
    nvidia.com/gpu.deploy.driver: "true"
status: {}


