apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nvubuntu
  name: nvubuntu
spec:
  containers:
  - command:
    - tail
    - -f
    - /dev/null
    image: nvidia/cuda:11.7.1-base-ubuntu22.04
    name: nvubuntu
    volumeMounts:
      - mountPath: "/app"
        name: app-pvc
    securityContext:
      runAsUser: 0
      privileged: true

    resources: {}
  serviceAccountName: sapriv
  nodeSelector:
    nvidia.com/gpu.deploy.driver: "true"

  dnsPolicy: ClusterFirst
  restartPolicy: Always

  volumes:
    - name: app-pvc
      persistentVolumeClaim:
        claimName: nv-data-pvc

status: {}


