apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: apiserver
  name: apiserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apiserver
  strategy: {}
  template:
    metadata:
      labels:
        app: apiserver
    spec:
      containers:
      - image: quay.io/anlixue/aiserver:v1.3
        name: aiserver
        command: ["/app/startapiserver.sh"]
        volumeMounts:
          - mountPath: "/app/cache"
            name: emmodel-pvc
          - mountPath: "/app/DB"
            name: db-pvc
        env:
        - name: LLM_SERVER_URL
          value: http://llmserver
        - name: LLM_SERVER_TYPE
          value: local
        - name: SENTENCE_TRANSFORMERS_HOME
          value: /app/cache
        - name: MODEL_NAME
          value: neural-chat 
        - name: MODEL_TEMPERATURE
          value: "0.2"
        - name: ACTION_MODEL_NAME
          value: neural-chat 
        - name: ACTION_MODEL_TEMPERATURE
          value: "0"
        - name: EMBEDDING_MODEL_NAME
          value: hkunlp/instructor-large
        - name: DB_DIRECTORY
          #value: /app/DB_Fusion
          value: /app/DB
        - name: PORT
          value: "5001"          
        - name: OCP_API_SERVER
          value: "https://api.bnr-sno-honda.fusion-sno-ibm.com:6443"          
        - name: OCP_LOGIN_TOKEN
          value: "sha256~GesXwBuGexQ4DTACEc3EhYk1DDBrYX8PUQ_SUS-k-H4"
      volumes:
        - name: emmodel-pvc
          persistentVolumeClaim:
            claimName: apiserver-emmodel-pvc
        - name: db-pvc
          persistentVolumeClaim:
            claimName: apiserver-db-pvc

